SET foreign_key_checks = 0;


CREATE TABLE PRODUCT (
	productID	INTEGER		NOT NULL AUTO_INCREMENT	,
	productName	VARCHAR(150)	NOT NULL		,
	modelNumber		CHAR(25) UNIQUE NOT NULL	,
	subcategoryID	INTEGER		NOT NULL 	,
	price		DECIMAL(10,2)	NOT NULL		,
	description	VARCHAR(1000)	NOT NULL		,
	qtyOnHand	INTEGER		NOT NULL 	,
	imagePath	CHAR(50),		
	 PRIMARY KEY (productID))
		AUTO_INCREMENT=100001
		ENGINE=INNODB
;

CREATE TABLE PERSON (
	personID	INTEGER		NOT NULL AUTO_INCREMENT	,
	login		CHAR(50)	UNIQUE NOT NULL		,
	password	CHAR(50)	NOT NULL		,
	securityQuesID	INTEGER	NOT NULL		,
	securityAnswer	CHAR(25)	NOT NULL		,
		PRIMARY KEY (personID))
		AUTO_INCREMENT=100001
		ENGINE=INNODB
;

CREATE TABLE SECURITY_QUESTION (
	securityQuesID	INTEGER		NOT NULL AUTO_INCREMENT	,
	question	CHAR(60)	NOT NULL		,
		PRIMARY KEY (securityQuesID))
		ENGINE=INNODB
;

CREATE TABLE CUSTOMER (
	customerID	INTEGER		NOT NULL AUTO_INCREMENT	,
	personID	INTEGER		UNIQUE NOT NULL		,
	firstName	CHAR(20)	NOT NULL		,
	middleName	CHAR(20)				,
	lastName	CHAR(30)	NOT NULL		,
	dateOfBirth	DATE					,
		PRIMARY KEY (customerID))
		AUTO_INCREMENT=100001
		ENGINE=INNODB
;


CREATE TABLE WISH_LIST (
	wishListID	INTEGER		NOT NULL AUTO_INCREMENT	,
	customerID	INTEGER		NOT NULL		,
	wishListName	CHAR(20)	NOT NULL DEFAULT 'default',
	createdDate	DATE					,
	lastUpdated	TIMESTAMP				,
		PRIMARY KEY (wishListID))
		AUTO_INCREMENT=100001
		ENGINE=INNODB
;

CREATE TABLE SALES_TAX (
	state		CHAR(2)		NOT NULL		,
	percent		DECIMAL(7,5)	NOT NULL		,
		PRIMARY KEY (state))
		ENGINE=INNODB
;


CREATE TABLE ORDERS (
	orderID		INTEGER		NOT NULL AUTO_INCREMENT	,
	customerID	INTEGER		NOT NULL		,
	numOfItems	INTEGER		NOT NULL		,
	itemSubtotal	DECIMAL(10,2)	NOT NULL		,
	shippingTotal	DECIMAL(8,2)	NOT NULL		,
	salesTaxPaid DECIMAL(8,2)	NOT NULL		,
	timePlaced	TIMESTAMP	,
	timeShipped	TIMESTAMP	DEFAULT 0		,
	transactNumber	CHAR(20)				,
		PRIMARY KEY (orderID))
		AUTO_INCREMENT=100001
		ENGINE=INNODB
;

CREATE TABLE PRODUCTS_IN_WISH_LIST (
	productsInWishListID	INTEGER		NOT NULL AUTO_INCREMENT	,
	wishListID	INTEGER		NOT NULL		,
	productID	INTEGER		NOT NULL		,
	quantity	SMALLINT	NOT NULL DEFAULT 1	,
	timeAdded	TIMESTAMP	,
		PRIMARY KEY (productsInWishListID),
		UNIQUE KEY (wishListID, productID))
		ENGINE = INNODB
;

CREATE TABLE ITEMS_ORDERED (
	itemsOrderedID	INTEGER		NOT NULL AUTO_INCREMENT	, 
	orderID		INTEGER		NOT NULL		,
	productID	INTEGER		NOT NULL		,
	unitPrice	DECIMAL(10,2)	NOT NULL		,
	itemQty		INTEGER		NOT NULL		,
		PRIMARY KEY (itemsOrderedID),
		UNIQUE KEY (orderID, productID))
		ENGINE=INNODB
;


CREATE TABLE REVIEW (
	reviewID	INTEGER		NOT NULL AUTO_INCREMENT	,
	productID	INTEGER		NOT NULL		,
	customerID	INTEGER		NOT NULL		,
	rating		SMALLINT	NOT NULL		,
	review		VARCHAR(2000)	NOT NULL		,
		PRIMARY KEY (reviewID))
		AUTO_INCREMENT = 100001
		ENGINE=INNODB
;

CREATE TABLE CATEGORY (
	categoryID		INTEGER		NOT NULL AUTO_INCREMENT ,
	categoryName	CHAR(20)	UNIQUE NOT NULL			,
		PRIMARY KEY (categoryID))
		AUTO_INCREMENT = 101
		ENGINE=INNODB
;

CREATE TABLE SUBCATEGORY (
	subcategoryID	INTEGER		NOT NULL AUTO_INCREMENT	,
	categoryID		INTEGER		NOT NULL				,
	subcategoryName	CHAR(30)	NOT NULL				,
		PRIMARY KEY (subcategoryID))
		AUTO_INCREMENT = 1001
		ENGINE=INNODB
;

CREATE TABLE SERVICE_CASE (
	caseID			INTEGER		NOT NULL AUTO_INCREMENT	,	
	customerID		INTEGER		NOT NULL				,
		PRIMARY KEY (caseID))
		AUTO_INCREMENT = 100001
		ENGINE = INNODB
;

CREATE TABLE MESSAGE (
	messageID		INTEGER		NOT NULL AUTO_INCREMENT	,
	caseID			INTEGER		NOT NULL				,
	personID		INTEGER		NOT NULL				,
	empOrCust		CHAR(1)		NOT NULL				,
	sequence		SMALLINT	NOT NULL				,
	message			VARCHAR(1000)	NOT NULL			,
		PRIMARY KEY (messageID))
		AUTO_INCREMENT=100001
		ENGINE=INNODB
;

CREATE TABLE USERS (
	userId INTEGER NOT NULL AUTO_INCREMENT,
	lastName CHAR (15) NOT NULL ,
	firstName CHAR(15) NOT NULL,
	mail CHAR(20) NOT NULL,
	password CHAR(50) NOT NULL,
		PRIMARY KEY (userID))
		 AUTO_INCREMENT=100001
		 ENGINE=INNODB
;

ALTER TABLE SERVICE_CASE
	ADD CONSTRAINT FK_CASE_TO_CUSTOMER
		FOREIGN KEY (customerID) REFERENCES CUSTOMER (customerID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
;

ALTER TABLE MESSAGE
	ADD CONSTRAINT FK_MESSAGE_TO_CASE
		FOREIGN KEY (caseID) REFERENCES SERVICE_CASE (caseID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
;

ALTER TABLE MESSAGE
	ADD CONSTRAINT FK_MESSAGE_TO_PERSON
		FOREIGN KEY (personID) REFERENCES PERSON (personID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
;

ALTER TABLE SUBCATEGORY
	ADD CONSTRAINT FK_SUB_TO_CATEGORY
		FOREIGN KEY (categoryID) REFERENCES CATEGORY (categoryID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
;

ALTER TABLE PRODUCT
	ADD CONSTRAINT FK_PRODUCT_TO_SUB
		FOREIGN KEY (subcategoryID)	REFERENCES SUBCATEGORY (subcategoryID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
;



ALTER TABLE REVIEW
	ADD CONSTRAINT FK_REVIEW_TO_PRODUCT
		FOREIGN KEY (productID) REFERENCES PRODUCT (productID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
;

ALTER TABLE REVIEW
	ADD CONSTRAINT FK_REVIEW_TO_CUSTOMER
		FOREIGN KEY (customerID) REFERENCES CUSTOMER (customerID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
;


ALTER TABLE WISH_LIST
	ADD CONSTRAINT FK_WISH_LIST_TO_CUSTOMER
		FOREIGN KEY (customerID) REFERENCES CUSTOMER (customerID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
;

ALTER TABLE PRODUCTS_IN_WISH_LIST
	ADD CONSTRAINT FK_PROD_IN_WISH_LIST_TO_LIST
		FOREIGN KEY (wishListID) REFERENCES WISH_LIST (wishListID)		
		ON UPDATE CASCADE
		ON DELETE CASCADE
;

ALTER TABLE PRODUCTS_IN_WISH_LIST
	ADD CONSTRAINT FK_PROD_IN_WISH_LIST_TO_PROD
		FOREIGN KEY (productID) REFERENCES PRODUCT (productID)		
		ON UPDATE CASCADE
		ON DELETE CASCADE
;


ALTER TABLE ORDERS
	ADD CONSTRAINT FK_ORDERS_TO_CUSTOMER
		FOREIGN KEY (customerID) REFERENCES CUSTOMER (customerID )
		ON UPDATE CASCADE
		ON DELETE CASCADE
;

ALTER TABLE ITEMS_ORDERED
	ADD CONSTRAINT FK_ITEMS_ORDERED_TO_ORDER
		FOREIGN KEY (orderID) REFERENCES ORDERS (orderID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
;

ALTER TABLE ITEMS_ORDERED
	ADD CONSTRAINT FK_ITEMS_ORDERED_TO_PRODUCT
		FOREIGN KEY (productID) REFERENCES PRODUCT (productID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
;

ALTER TABLE CUSTOMER
	ADD CONSTRAINT FK_CUSTOMER_TO_PERSON
		FOREIGN KEY (personID) REFERENCES PERSON (personID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
;


ALTER TABLE PERSON
	ADD CONSTRAINT FK_PERSON_TO_SECURITY
		FOREIGN KEY (securityQuesID) REFERENCES SECURITY_QUESTION (securityQuesID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
;

SET foreign_key_checks = 1;


INSERT INTO `category` VALUES (3,'Bijoux'),(2,'Cosmetiques'),(4,'Maroquineries'),(1,'Vêtements');



INSERT INTO `subcategory` VALUES (1,'Homme',1),(2,'Femmes',1),(3,'Enfants',1),(4,'Homme',2),(5,'Femmes',2),(6,'Enfants',2),(7,'Homme',3),(8,'Femmes',3),(9,'Enfants',3),(10,'Homme',4),(11,'Femmes',4),(12,'Enfants',4);

--
-- Table structure for table `users`
--
