// default package
// Generated 1 janv. 2015 18:48:45 by Hibernate Tools 3.4.0.CR1

package com.monyLady.myapp.model;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "monylady", uniqueConstraints = @UniqueConstraint(columnNames = "categoryName"))
public class Category implements java.io.Serializable {

	private Integer categoryId;
	private String categoryName;
	private Set<Subcategory> subcategories = new HashSet<Subcategory>(0);

	public Category() {
	}

	public Category(String categoryName) {
		this.categoryName = categoryName;
	}

	public Category(String categoryName, Set<Subcategory> subcategories) {
		this.categoryName = categoryName;
		this.subcategories = subcategories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "categoryID", unique = true, nullable = false)
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "categoryName", unique = true, nullable = false, length = 20)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<Subcategory> getSubcategories() {
		return this.subcategories;
	}

	public void setSubcategories(Set<Subcategory> subcategories) {
		this.subcategories = subcategories;
	}

}
