// default package
// Generated 1 janv. 2015 18:48:45 by Hibernate Tools 3.4.0.CR1

package com.monyLady.myapp.model;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ItemsOrdered generated by hbm2java
 */
@Entity
@Table(name = "items_ordered", catalog = "monylady", uniqueConstraints = @UniqueConstraint(columnNames = {
		"orderID", "productID" }))
public class ItemsOrdered implements java.io.Serializable {

	private Integer itemsOrderedId;
	private Orders orders;
	private Product product;
	private BigDecimal unitPrice;
	private int itemQty;

	public ItemsOrdered() {
	}

	public ItemsOrdered(Orders orders, Product product, BigDecimal unitPrice,
			int itemQty) {
		this.orders = orders;
		this.product = product;
		this.unitPrice = unitPrice;
		this.itemQty = itemQty;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "itemsOrderedID", unique = true, nullable = false)
	public Integer getItemsOrderedId() {
		return this.itemsOrderedId;
	}

	public void setItemsOrderedId(Integer itemsOrderedId) {
		this.itemsOrderedId = itemsOrderedId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "orderID", nullable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productID", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "unitPrice", nullable = false, precision = 10)
	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "itemQty", nullable = false)
	public int getItemQty() {
		return this.itemQty;
	}

	public void setItemQty(int itemQty) {
		this.itemQty = itemQty;
	}

}
