
package com.monyLady.myapp.model;


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;



/**
 * Person generated by hbm2java
 */
@Entity
//@Table(name = "person", catalog = "monylady", uniqueConstraints = @UniqueConstraint(columnNames = "login"))
@Table(name = "person")
public class Person  {

	private Integer personId;
	private SecurityQuestion securityQuestion;
	private String login;
	private String password;
	private String securityAnswer;
	private Set<Customer> customers = new HashSet<Customer>(0);
	private Set<Message> messages = new HashSet<Message>(0);

	public Person() {
	}

	
	/*
	public Person(SecurityQuestion securityQuestion, String login,
			String password, String securityAnswer) {
		this.securityQuestion = securityQuestion;
		this.login = login;
		this.password = password;
		this.securityAnswer = securityAnswer;
	}

	public Person(SecurityQuestion securityQuestion, String login,
			String password, String securityAnswer, Set<Customer> customers,
			Set<Message> messages) {
		this.securityQuestion = securityQuestion;
		this.login = login;
		this.password = password;
		this.securityAnswer = securityAnswer;
		this.customers = customers;
		this.messages = messages;
	}
    */
	@Id
	@GeneratedValue(strategy= GenerationType.IDENTITY)
	@Column(name = "personID", unique = true, nullable = false)
	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "securityQuesID", nullable = false)
	public SecurityQuestion getSecurityQuestion() {
		return this.securityQuestion;
	}

	public void setSecurityQuestion(SecurityQuestion securityQuestion) {
		this.securityQuestion = securityQuestion;
	}

	@Column(name = "login", unique = true, nullable = false, length = 50)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "securityAnswer", nullable = false, length = 25)
	public String getSecurityAnswer() {
		return this.securityAnswer;
	}

	public void setSecurityAnswer(String securityAnswer) {
		this.securityAnswer = securityAnswer;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "person")
	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "person")
	public Set<Message> getMessages() {
		return this.messages;
	}

	public void setMessages(Set<Message> messages) {
		this.messages = messages;
	}

	public boolean exist() {
		// TODO Auto-generated method stub
		return true;
	}

}
