// default package
// Generated 1 janv. 2015 18:48:45 by Hibernate Tools 3.4.0.CR1


package com.monyLady.myapp.model;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "monylady", uniqueConstraints = @UniqueConstraint(columnNames = "modelNumber"))
public class Product implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer productId;
	private Subcategory subcategory;
	private String productName;
	private String modelNumber;
	private BigDecimal price;
	private String description;
	private int qtyOnHand;
	private String imagePath;
	private Set<ItemsOrdered> itemsOrdereds = new HashSet<ItemsOrdered>(0);
	private Set<Review> reviews = new HashSet<Review>(0);
	private Set<ProductsInWishList> productsInWishLists = new HashSet<ProductsInWishList>(
			0);
	

	public Product() {
	}

	/*
	public Product(Subcategory subcategory, String productName,
			String modelNumber, BigDecimal price, String description,
			int qtyOnHand) {
		this.subcategory = subcategory;
		this.productName = productName;
		this.modelNumber = modelNumber;
		this.price = price;
		this.description = description;
		this.qtyOnHand = qtyOnHand;
	}
	*/
	
	public Product( Subcategory subcategory, String productName,
			String modelNumber, BigDecimal price, String description,
			int qtyOnHand, String imagePath) {
		
		this.subcategory=subcategory;
		this.productName = productName;
		this.modelNumber = modelNumber;
		this.price = price;
		this.description = description;
		this.imagePath= imagePath;
		this.qtyOnHand = qtyOnHand;
	}

/*
	public Product(Subcategory subcategory, String productName,
			String modelNumber, BigDecimal price, String description,
			int qtyOnHand, String imagePath, Set<ItemsOrdered> itemsOrdereds,
			Set<Review> reviews, Set<ProductsInWishList> productsInWishLists) {
		this.subcategory = subcategory;
		this.productName = productName;
		this.modelNumber = modelNumber;
		this.price = price;
		this.description = description;
		this.qtyOnHand = qtyOnHand;
		this.imagePath = imagePath;
		this.itemsOrdereds = itemsOrdereds;
		this.reviews = reviews;
		this.productsInWishLists = productsInWishLists;
	}
*/
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "productID", unique = true, nullable = false)
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subcategoryID", nullable = false)
	public Subcategory getSubcategory() {
		return this.subcategory;
	}

	public void setSubcategory(Subcategory subcategory) {
		this.subcategory = subcategory;
	}

	@Column(name = "productName", nullable = false, length = 150)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "modelNumber", unique = true, nullable = false, length = 25)
	public String getModelNumber() {
		return this.modelNumber;
	}

	public void setModelNumber(String modelNumber) {
		this.modelNumber = modelNumber;
	}

	@Column(name = "price", nullable = false, precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "description", nullable = false, length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "qtyOnHand", nullable = false)
	public int getQtyOnHand() {
		return this.qtyOnHand;
	}

	public void setQtyOnHand(int qtyOnHand) {
		this.qtyOnHand = qtyOnHand;
	}

	@Column(name = "imagePath", length = 50)
	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ItemsOrdered> getItemsOrdereds() {
		return this.itemsOrdereds;
	}

	public void setItemsOrdereds(Set<ItemsOrdered> itemsOrdereds) {
		this.itemsOrdereds = itemsOrdereds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Review> getReviews() {
		return this.reviews;
	}

	public void setReviews(Set<Review> reviews) {
		this.reviews = reviews;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProductsInWishList> getProductsInWishLists() {
		return this.productsInWishLists;
	}

	public void setProductsInWishLists(
			Set<ProductsInWishList> productsInWishLists) {
		this.productsInWishLists = productsInWishLists;
	}

	
	

}
