// default package
// Generated 1 janv. 2015 18:48:45 by Hibernate Tools 3.4.0.CR1


package com.monyLady.myapp.model;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SalesTax generated by hbm2java
 */
@Entity
@Table(name = "sales_tax", catalog = "monylady")
public class SalesTax implements java.io.Serializable {

	private String state;
	private BigDecimal percent;

	public SalesTax() {
	}

	public SalesTax(String state, BigDecimal percent) {
		this.state = state;
		this.percent = percent;
	}

	@Id
	@Column(name = "state", unique = true, nullable = false, length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "percent", nullable = false, precision = 7, scale = 5)
	public BigDecimal getPercent() {
		return this.percent;
	}

	public void setPercent(BigDecimal percent) {
		this.percent = percent;
	}

}
