// default package
// Generated 1 janv. 2015 18:48:45 by Hibernate Tools 3.4.0.CR1


package com.monyLady.myapp.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SecurityQuestion generated by hbm2java
 */
@Entity
@Table(name = "security_question", catalog = "monylady")
public class SecurityQuestion implements java.io.Serializable {

	private Integer securityQuesId;
	private String question;
	private Set<Person> persons = new HashSet<Person>(0);

	public SecurityQuestion() {
	}

	public SecurityQuestion(String question) {
		this.question = question;
	}

	public SecurityQuestion(String question, Set<Person> persons) {
		this.question = question;
		this.persons = persons;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "securityQuesID", unique = true, nullable = false)
	public Integer getSecurityQuesId() {
		return this.securityQuesId;
	}

	public void setSecurityQuesId(Integer securityQuesId) {
		this.securityQuesId = securityQuesId;
	}

	@Column(name = "question", nullable = false, length = 60)
	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "securityQuestion")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

}
