// default package
// Generated 1 janv. 2015 18:48:45 by Hibernate Tools 3.4.0.CR1


package com.monyLady.myapp.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;





/**
 * WishList generated by hbm2java
 */
@Entity
@Table(name = "wish_list", catalog = "monylady")
public class WishList  implements java.io.Serializable {
	
	

	private Integer wishListId;
	private Customer customer;
	private String wishListName;
	private Date createdDate;
	private Date lastUpdated;
	private Set<ProductsInWishList> productsInWishLists = new HashSet<ProductsInWishList>(
			0);

	public WishList() {
	}

	public WishList(Customer customer, String wishListName, Date lastUpdated) {
		this.customer = customer;
		this.wishListName = wishListName;
		this.lastUpdated = lastUpdated;
	}

	public WishList(Customer customer, String wishListName, Date createdDate,
			Date lastUpdated, Set<ProductsInWishList> productsInWishLists) {
		this.customer = customer;
		this.wishListName = wishListName;
		this.createdDate = createdDate;
		this.lastUpdated = lastUpdated;
		this.productsInWishLists = productsInWishLists;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "wishListID", unique = true, nullable = false)
	public Integer getWishListId() {
		return this.wishListId;
	}

	public void setWishListId(Integer wishListId) {
		this.wishListId = wishListId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customerID", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "wishListName", nullable = false, length = 20)
	public String getWishListName() {
		return this.wishListName;
	}

	public void setWishListName(String wishListName) {
		this.wishListName = wishListName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdDate", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastUpdated", nullable = false, length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wishList")
	public Set<ProductsInWishList> getProductsInWishLists() {
		return this.productsInWishLists;
	}

	public void setProductsInWishLists(
			Set<ProductsInWishList> productsInWishLists) {
		this.productsInWishLists = productsInWishLists;
	}

}
